# Generated by Django 5.1.5 on 2025-02-15 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_appointment', models.BooleanField(default=True)),
                ('notify_reminder', models.BooleanField(default=True)),
                ('allowed_stages', models.ManyToManyField(to='visits.schoolstage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.IntegerField(help_text='Duración en minutos')),
                ('is_active', models.BooleanField(default=True)),
                ('repeat_type', models.CharField(choices=[('once', 'Única vez'), ('weekly', 'Semanal')], default='once', max_length=10)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('weekday', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.schoolstage')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.staffprofile')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date', 'start_time'], name='visits_avai_date_671d48_idx'), models.Index(fields=['staff', 'is_active'], name='visits_avai_staff_i_55a110_idx')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=200)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_phone', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Realizada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas internas del profesor')),
                ('follow_up_date', models.DateField(blank=True, help_text='Fecha de seguimiento', null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.schoolstage')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.staffprofile')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='visits_appo_date_22f365_idx'), models.Index(fields=['staff', 'date'], name='visits_appo_staff_i_397195_idx'), models.Index(fields=['status'], name='visits_appo_status_a418ba_idx')],
            },
        ),
    ]
