# Generated by Django 5.1.5 on 2025-01-24 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.IntegerField(help_text='Duración en minutos')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.staffprofile')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.schoolstage')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
