# Generated by Django 5.2.4 on 2025-07-29 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=1, help_text='Orden de visualización dentro de la etapa')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='visits.schoolstage')),
            ],
            options={
                'ordering': ['stage', 'order'],
                'unique_together': {('stage', 'name')},
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Curso específico dentro de la etapa', null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.course'),
        ),
    ]
