# Generated by Django 5.1.5 on 2025-01-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_availabilityslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='repeat_type',
            field=models.CharField(choices=[('once', 'Única vez'), ('weekly', 'Semanal')], default='once', max_length=10),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='weekday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
