# Generated by Django 5.2.4 on 2025-08-04 20:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_course_appointment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['cancellation_token'], name='visits_appo_cancell_0b557e_idx'),
        ),
    ]
