# Generated by Django 5.1.5 on 2025-01-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_availabilityslot_month_availabilityslot_repeat_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date']},
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['date', 'start_time'], name='visits_avai_date_671d48_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['staff', 'is_active'], name='visits_avai_staff_i_55a110_idx'),
        ),
    ]
