# Generated by Django 5.1.5 on 2025-01-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
