# Generated by Django 5.1.5 on 2025-01-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_availabilityslot_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
