# Generated by Django 5.1.5 on 2025-02-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_appointment_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visitor_phone',
            field=models.CharField(max_length=9),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date'], name='visits_appo_date_22f365_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['staff', 'date'], name='visits_appo_staff_i_397195_idx'),
        ),
    ]
