# Generated by Django 5.1.5 on 2025-02-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_alter_appointment_visitor_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visitor_phone',
            field=models.CharField(max_length=20),
        ),
    ]
