# Generated by Django 5.1.5 on 2025-02-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0008_alter_appointment_visitor_phone'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='availabilityslot',
            name='visits_avai_staff_i_55a110_idx',
        ),
        migrations.RemoveField(
            model_name='availabilityslot',
            name='is_active',
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['staff'], name='visits_avai_staff_i_0ecffb_idx'),
        ),
    ]
