# Generated by Django 5.1.5 on 2025-02-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0009_remove_availabilityslot_visits_avai_staff_i_55a110_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='availabilityslot',
            name='visits_avai_staff_i_0ecffb_idx',
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['staff', 'is_active'], name='visits_avai_staff_i_55a110_idx'),
        ),
    ]
