# Generated by Django 5.1.5 on 2025-02-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0010_remove_availabilityslot_visits_avai_staff_i_0ecffb_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityslot',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='availabilityslot',
            name='visits_avai_date_671d48_idx',
        ),
        migrations.RemoveIndex(
            model_name='availabilityslot',
            name='visits_avai_staff_i_55a110_idx',
        ),
    ]
