# Generated by Django 5.1.5 on 2025-02-09 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0011_alter_availabilityslot_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='appointment_attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interested', 'Interesados'), ('pending', 'Pendiente decisión'), ('confirmed', 'Confirman matriculación'), ('rejected', 'No interesados')], default='pending', max_length=20)),
                ('next_action', models.CharField(blank=True, max_length=200)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('internal_comments', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False, help_text='Si es privada, solo visible para el staff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('ical', 'iCalendar')], default='pdf', max_length=10)),
                ('include_notes', models.BooleanField(default=True)),
                ('include_attachments', models.BooleanField(default=False)),
                ('last_export', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_appointment', 'Nueva Cita'), ('reminder', 'Recordatorio'), ('status_change', 'Cambio Estado'), ('summary', 'Resumen')], max_length=20)),
                ('recipient', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Enviado'), ('failed', 'Fallido'), ('pending', 'Pendiente')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='availabilityslot',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('completed', 'Realizada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='email_new_appointment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='email_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='email_weekly_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='visits_appo_status_a418ba_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['date', 'start_time'], name='visits_avai_date_671d48_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['staff', 'is_active'], name='visits_avai_staff_i_55a110_idx'),
        ),
        migrations.AddField(
            model_name='appointmentattachment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='visits.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentfollowup',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up', to='visits.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentfollowup',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentnote',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='visits.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportconfig',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visits.staffprofile'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='visits.appointment'),
        ),
        migrations.AddIndex(
            model_name='appointmentfollowup',
            index=models.Index(fields=['status'], name='visits_appo_status_2ec4d3_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentfollowup',
            index=models.Index(fields=['next_action_date'], name='visits_appo_next_ac_b0d935_idx'),
        ),
        migrations.AddIndex(
            model_name='exportconfig',
            index=models.Index(fields=['staff'], name='visits_expo_staff_i_edbdb4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['appointment', 'notification_type'], name='visits_noti_appoint_b9aa49_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['sent_at'], name='visits_noti_sent_at_21c4fd_idx'),
        ),
    ]
