# Generated by Django 5.1.5 on 2025-02-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0012_appointmentattachment_appointmentfollowup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentfollowup',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='appointmentfollowup',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='appointmentnote',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='appointmentnote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='exportconfig',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='email_new_appointment',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='email_reminder',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='email_weekly_summary',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Realizada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='AppointmentAttachment',
        ),
        migrations.DeleteModel(
            name='AppointmentFollowUp',
        ),
        migrations.DeleteModel(
            name='AppointmentNote',
        ),
        migrations.DeleteModel(
            name='ExportConfig',
        ),
        migrations.DeleteModel(
            name='NotificationLog',
        ),
    ]
