# Generated by Django 5.1.5 on 2025-02-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0013_remove_appointmentfollowup_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
