# Generated by Django 5.1.5 on 2025-02-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0015_appointment_follow_up_date_appointment_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
    ]
