# Generated by Django 5.1.5 on 2025-02-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0016_remove_appointment_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='follow_up_date',
            field=models.DateField(blank=True, help_text='Fecha de seguimiento', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas internas del profesor'),
        ),
    ]
