# Generated by Django 5.1.5 on 2025-02-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0018_appointment_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='notify_new_appointment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='notify_reminder',
            field=models.BooleanField(default=True),
        ),
    ]
